services:
  db:
    image: postgres:15
    container_name: onepiece-db
    restart: always
    environment:
      POSTGRES_DB: onepiece
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: onepiece-app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://onepiece-db:5432/onepiece
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APITCG_API_KEY: db4b10b9cf7e7f3560804c5a473ef2690d5821f03f8cd0ffea90f19f95a067b6

volumes:
  db_data:
